### PR TITLE
Add my new songs

### PR DESCRIPTION
**Pull request by H-A-M-G-E-R**

### CODE REVIEW

**Comment by H-A-M-G-E-R** [comment]
There's a catch: this patch is needed for most of my ALttP ports to play correctly ingame without the echo permanently stopping.
https://forum.metroidconstruction.com/index.php/topic,145.msg73471.html#msg73471

**Comment by flohgh** [comment]
> There's a catch: this patch is needed for most of my ALttP ports to play correctly ingame without the echo permanently stopping. https://forum.metroidconstruction.com/index.php/topic,145.msg73471.html#msg73471

Hello, I'm starting to import this impressive amount of new songs! Do you confirm that if I systematically apply the 1.02 version of the linked patch when any custom music is used, it won't cause issues with other custom music, or even vanilla music? And how needed is asar 1.90? We use thedopefish modified version of asar, that is branched from 1.81. It chokes on the "execute $1500" last statement. I replaced that with dw 0, $1500 which should work?

**Comment by flohgh** [comment]
As a side note, changing filenames of already existing custom music, and trying to slip in a completely music-unrelated change in the preview of Super Junkoid sprite for some reason is not what I would call good practice...

Since a lot of data files may be processed by shell scripts, it's more manageable to have filenames without special characters, especially whitespace. That's why the song track name is a metadata, and is not extracted from filename.

**Comment by H-A-M-G-E-R** [comment]
Here's an updated version that also speeds up the delay after the Nintendo logo: https://forum.metroidconstruction.com/index.php/topic,145.msg73480.html#msg73480

**Comment by H-A-M-G-E-R** [comment]
> > There's a catch: this patch is needed for most of my ALttP ports to play correctly ingame without the echo permanently stopping. https://forum.metroidconstruction.com/index.php/topic,145.msg73471.html#msg73471
> 
> Hello, I'm starting to import this impressive amount of new songs! Do you confirm that if I systematically apply the 1.02 version of the linked patch when any custom music is used, it won't cause issues with other custom music, or even vanilla music? And how needed is asar 1.90? We use thedopefish modified version of asar, that is branched from 1.81. It chokes on the "execute $1500" last statement. I replaced that with dw 0, $1500 which should work?

It doesn't cause issues with all other songs. It only affects sound effects that they never have echo which is the intended behavior.

**Pull request merged**
